# Generated by Django 5.2.5 on 2025-10-04 09:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_expensecategory_expense_expenseapproval_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expenseapproval',
            unique_together={('expense', 'step_order')},
        ),
        migrations.AddField(
            model_name='expense',
            name='current_step',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='expenseapproval',
            name='approver_type',
            field=models.CharField(default='manager', max_length=20),
        ),
        migrations.CreateModel(
            name='ApprovalFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_flows', to='api.company')),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='approval_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.approvalflow'),
        ),
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rule_type', models.CharField(choices=[('sequential', 'Sequential Flow'), ('percentage', 'Percentage Rule'), ('specific_approver', 'Specific Approver Rule'), ('hybrid', 'Hybrid Rule')], default='sequential', max_length=20)),
                ('percentage_threshold', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('amount_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_manager_approver', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='api.company')),
                ('specific_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specific_approval_rules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='approvalflow',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='api.approvalrule'),
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver_type', models.CharField(choices=[('manager', 'Manager'), ('admin', 'Admin'), ('finance', 'Finance'), ('director', 'Director'), ('specific_user', 'Specific User')], max_length=20)),
                ('step_order', models.IntegerField()),
                ('is_required', models.BooleanField(default=True)),
                ('approval_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.approvalflow')),
                ('specific_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['step_order'],
                'unique_together': {('approval_flow', 'step_order')},
            },
        ),
    ]
